#! /bin/sh

# source variables
. ~/.config/bspwm/panel/panel_colors

if [ $(pgrep -cx panel) -gt 1 ] ; then
  printf "%s\n" "The panel is already running." >&2
  exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT

bspc control --subscribe > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &
conky -c ~/.config/bspwm/panel/panel_conky > "$PANEL_FIFO" &

cat "$PANEL_FIFO" | ~/.config/bspwm/panel/panel_dzen2 -f "$FONT_FAMILY" -s "$FONT_SIZE" \
  | dzen2 -h $PANEL_HEIGHT -dock -ta l -title-name panel \
  -fn "${FONT_FAMILY}:pixelsize=${FONT_SIZE}" -fg "$COLOR_FOREGROUND" \
  -bg "$COLOR_BACKGROUND"
